development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  database: meeting-bot

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  database: notification